language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t devileyes/docker-react-deploy -f Dockerfile.dev .

script:
  - docker run -e CI=true devileyes/docker-react-deploy npm run test -- --coverage
