sudo: required
services:
  - docker

before_install:
  - docker build -t devileyes/docker-react-deploy -f Dockerfile.dev .

script:
  - docker run devileyes/docker-react-deploy npm run test -- --coverage
