FROM node:alpine

RUN mkdir -p /app && chown -R node:node /app
WORKDIR /app

RUN chgrp -R 0 /app && chmod -R g+rwX /app

COPY package.json .
USER 1000
RUN npm i


COPY --chown=node:node  . .


CMD ["npm","run","start"]